// ============================================================
// Daily English 콘텐츠 데이터
// 단어 추가 방법: WORDS 배열에 같은 형식으로 한 줄 추가하면 끝.
// en=영어, ko=뜻, pos=품사, exEn/exKo=예문, unit=유닛 id
// ============================================================

const LEVELS = [
  { id: "lv1", title: "Lv.1 기초", desc: "왕초보 · 생존 단어와 기본 인사 (80단어)" },
  { id: "lv2", title: "Lv.2 일상 중급", desc: "일상 대화의 뼈대가 되는 생활 어휘 (100단어)" },
  { id: "lv3", title: "Lv.3 일상 고급", desc: "성인 대화 · 뉴스 · 구동사 · 미묘한 감정 (80단어)" },
];

const UNITS = [
  { id: "u101", level: "lv1", title: "인사와 기본 표현" },
  { id: "u102", level: "lv1", title: "시간과 날짜" },
  { id: "u103", level: "lv1", title: "가족과 사람" },
  { id: "u104", level: "lv1", title: "음식과 식사" },
  { id: "u105", level: "lv1", title: "일상 동작" },
  { id: "u106", level: "lv1", title: "장소와 방향" },
  { id: "u107", level: "lv1", title: "쇼핑과 돈" },
  { id: "u108", level: "lv1", title: "감정과 상태" },
  { id: "u201", level: "lv2", title: "집과 생활" },
  { id: "u202", level: "lv2", title: "하루 일과" },
  { id: "u203", level: "lv2", title: "관계와 소통" },
  { id: "u204", level: "lv2", title: "감정 표현" },
  { id: "u205", level: "lv2", title: "음식과 요리" },
  { id: "u206", level: "lv2", title: "건강과 운동" },
  { id: "u207", level: "lv2", title: "쇼핑과 소비" },
  { id: "u208", level: "lv2", title: "여행과 교통" },
  { id: "u209", level: "lv2", title: "날씨와 환경" },
  { id: "u210", level: "lv2", title: "의견과 대화" },
  { id: "u301", level: "lv3", title: "직장과 업무" },
  { id: "u302", level: "lv3", title: "돈과 경제" },
  { id: "u303", level: "lv3", title: "사회와 뉴스" },
  { id: "u304", level: "lv3", title: "성격과 태도" },
  { id: "u305", level: "lv3", title: "시간과 계획" },
  { id: "u306", level: "lv3", title: "문제와 해결" },
  { id: "u307", level: "lv3", title: "필수 구동사" },
  { id: "u308", level: "lv3", title: "미묘한 감정" },
];

const WORDS = [
  // ---------- Lv.1 기초 ----------
  { id: "w001", en: "hello", ko: "안녕하세요", pos: "감탄사", exEn: "Hello! Nice to meet you.", exKo: "안녕하세요! 만나서 반가워요.", unit: "u101" },
  { id: "w002", en: "goodbye", ko: "안녕히 가세요", pos: "감탄사", exEn: "Goodbye! See you tomorrow.", exKo: "안녕히 가세요! 내일 봐요.", unit: "u101" },
  { id: "w003", en: "please", ko: "부탁합니다", pos: "부사", exEn: "One coffee, please.", exKo: "커피 한 잔 부탁합니다.", unit: "u101" },
  { id: "w004", en: "thank you", ko: "감사합니다", pos: "표현", exEn: "Thank you for your help.", exKo: "도와주셔서 감사합니다.", unit: "u101" },
  { id: "w005", en: "sorry", ko: "미안합니다", pos: "형용사", exEn: "Sorry, I'm late.", exKo: "늦어서 미안합니다.", unit: "u101" },
  { id: "w006", en: "excuse me", ko: "실례합니다", pos: "표현", exEn: "Excuse me, where is the bathroom?", exKo: "실례합니다, 화장실이 어디예요?", unit: "u101" },
  { id: "w007", en: "yes", ko: "네", pos: "부사", exEn: "Yes, that's right.", exKo: "네, 맞아요.", unit: "u101" },
  { id: "w008", en: "no", ko: "아니요", pos: "부사", exEn: "No, thank you.", exKo: "아니요, 괜찮습니다.", unit: "u101" },
  { id: "w009", en: "okay", ko: "좋아요, 알겠어요", pos: "감탄사", exEn: "Okay, let's go.", exKo: "좋아요, 갑시다.", unit: "u101" },
  { id: "w010", en: "welcome", ko: "환영합니다", pos: "감탄사", exEn: "Welcome to Korea!", exKo: "한국에 오신 것을 환영합니다!", unit: "u101" },
  { id: "w011", en: "today", ko: "오늘", pos: "부사", exEn: "What day is it today?", exKo: "오늘 무슨 요일이에요?", unit: "u102" },
  { id: "w012", en: "tomorrow", ko: "내일", pos: "부사", exEn: "I will call you tomorrow.", exKo: "내일 전화할게요.", unit: "u102" },
  { id: "w013", en: "yesterday", ko: "어제", pos: "부사", exEn: "I was busy yesterday.", exKo: "어제는 바빴어요.", unit: "u102" },
  { id: "w014", en: "morning", ko: "아침", pos: "명사", exEn: "I drink coffee every morning.", exKo: "저는 매일 아침 커피를 마셔요.", unit: "u102" },
  { id: "w015", en: "afternoon", ko: "오후", pos: "명사", exEn: "See you this afternoon.", exKo: "오늘 오후에 봐요.", unit: "u102" },
  { id: "w016", en: "evening", ko: "저녁", pos: "명사", exEn: "Good evening, everyone!", exKo: "여러분, 좋은 저녁이에요!", unit: "u102" },
  { id: "w017", en: "night", ko: "밤", pos: "명사", exEn: "Good night. Sleep well.", exKo: "잘 자요. 푹 주무세요.", unit: "u102" },
  { id: "w018", en: "week", ko: "주, 일주일", pos: "명사", exEn: "I exercise three times a week.", exKo: "저는 일주일에 세 번 운동해요.", unit: "u102" },
  { id: "w019", en: "month", ko: "달, 월", pos: "명사", exEn: "My birthday is next month.", exKo: "제 생일은 다음 달이에요.", unit: "u102" },
  { id: "w020", en: "year", ko: "년, 해", pos: "명사", exEn: "Happy new year!", exKo: "새해 복 많이 받으세요!", unit: "u102" },
  { id: "w021", en: "family", ko: "가족", pos: "명사", exEn: "I love my family.", exKo: "저는 제 가족을 사랑해요.", unit: "u103" },
  { id: "w022", en: "mother", ko: "어머니", pos: "명사", exEn: "My mother is a teacher.", exKo: "저희 어머니는 선생님이에요.", unit: "u103" },
  { id: "w023", en: "father", ko: "아버지", pos: "명사", exEn: "My father likes fishing.", exKo: "저희 아버지는 낚시를 좋아하세요.", unit: "u103" },
  { id: "w024", en: "sister", ko: "언니, 누나, 여동생", pos: "명사", exEn: "I have one sister.", exKo: "저는 여동생이 한 명 있어요.", unit: "u103" },
  { id: "w025", en: "brother", ko: "형, 오빠, 남동생", pos: "명사", exEn: "My brother is tall.", exKo: "제 형은 키가 커요.", unit: "u103" },
  { id: "w026", en: "friend", ko: "친구", pos: "명사", exEn: "She is my best friend.", exKo: "그녀는 제 가장 친한 친구예요.", unit: "u103" },
  { id: "w027", en: "child", ko: "아이", pos: "명사", exEn: "The child is smiling.", exKo: "그 아이가 웃고 있어요.", unit: "u103" },
  { id: "w028", en: "people", ko: "사람들", pos: "명사", exEn: "Many people like this song.", exKo: "많은 사람들이 이 노래를 좋아해요.", unit: "u103" },
  { id: "w029", en: "name", ko: "이름", pos: "명사", exEn: "What is your name?", exKo: "이름이 뭐예요?", unit: "u103" },
  { id: "w030", en: "age", ko: "나이", pos: "명사", exEn: "We are the same age.", exKo: "우리는 나이가 같아요.", unit: "u103" },
  { id: "w031", en: "food", ko: "음식", pos: "명사", exEn: "Korean food is delicious.", exKo: "한국 음식은 맛있어요.", unit: "u104" },
  { id: "w032", en: "water", ko: "물", pos: "명사", exEn: "Can I have some water?", exKo: "물 좀 주시겠어요?", unit: "u104" },
  { id: "w033", en: "breakfast", ko: "아침 식사", pos: "명사", exEn: "I had toast for breakfast.", exKo: "아침으로 토스트를 먹었어요.", unit: "u104" },
  { id: "w034", en: "lunch", ko: "점심 식사", pos: "명사", exEn: "Let's have lunch together.", exKo: "같이 점심 먹어요.", unit: "u104" },
  { id: "w035", en: "dinner", ko: "저녁 식사", pos: "명사", exEn: "Dinner is ready.", exKo: "저녁 준비됐어요.", unit: "u104" },
  { id: "w036", en: "coffee", ko: "커피", pos: "명사", exEn: "I need a cup of coffee.", exKo: "커피 한 잔이 필요해요.", unit: "u104" },
  { id: "w037", en: "delicious", ko: "맛있는", pos: "형용사", exEn: "This soup is delicious.", exKo: "이 수프는 맛있어요.", unit: "u104" },
  { id: "w038", en: "hungry", ko: "배고픈", pos: "형용사", exEn: "I'm so hungry.", exKo: "너무 배고파요.", unit: "u104" },
  { id: "w039", en: "eat", ko: "먹다", pos: "동사", exEn: "What do you want to eat?", exKo: "뭐 먹고 싶어요?", unit: "u104" },
  { id: "w040", en: "drink", ko: "마시다", pos: "동사", exEn: "Drink more water.", exKo: "물을 더 마시세요.", unit: "u104" },
  { id: "w041", en: "go", ko: "가다", pos: "동사", exEn: "I go to work by bus.", exKo: "저는 버스로 출근해요.", unit: "u105" },
  { id: "w042", en: "come", ko: "오다", pos: "동사", exEn: "Come here, please.", exKo: "이리로 와 주세요.", unit: "u105" },
  { id: "w043", en: "see", ko: "보다", pos: "동사", exEn: "See you later!", exKo: "나중에 봐요!", unit: "u105" },
  { id: "w044", en: "buy", ko: "사다", pos: "동사", exEn: "I want to buy a new phone.", exKo: "새 휴대폰을 사고 싶어요.", unit: "u105" },
  { id: "w045", en: "make", ko: "만들다", pos: "동사", exEn: "I can make pasta.", exKo: "저는 파스타를 만들 수 있어요.", unit: "u105" },
  { id: "w046", en: "work", ko: "일하다", pos: "동사", exEn: "I work from nine to six.", exKo: "저는 9시부터 6시까지 일해요.", unit: "u105" },
  { id: "w047", en: "sleep", ko: "자다", pos: "동사", exEn: "I sleep seven hours a day.", exKo: "저는 하루에 7시간 자요.", unit: "u105" },
  { id: "w048", en: "walk", ko: "걷다", pos: "동사", exEn: "Let's walk to the park.", exKo: "공원까지 걸어가요.", unit: "u105" },
  { id: "w049", en: "help", ko: "돕다", pos: "동사", exEn: "Can you help me?", exKo: "저 좀 도와주시겠어요?", unit: "u105" },
  { id: "w050", en: "study", ko: "공부하다", pos: "동사", exEn: "I study English every day.", exKo: "저는 매일 영어를 공부해요.", unit: "u105" },
  { id: "w051", en: "home", ko: "집", pos: "명사", exEn: "I want to go home.", exKo: "집에 가고 싶어요.", unit: "u106" },
  { id: "w052", en: "school", ko: "학교", pos: "명사", exEn: "The school is near my house.", exKo: "학교는 우리 집 근처에 있어요.", unit: "u106" },
  { id: "w053", en: "store", ko: "가게", pos: "명사", exEn: "The store opens at ten.", exKo: "그 가게는 10시에 열어요.", unit: "u106" },
  { id: "w054", en: "hospital", ko: "병원", pos: "명사", exEn: "Where is the nearest hospital?", exKo: "가장 가까운 병원이 어디예요?", unit: "u106" },
  { id: "w055", en: "left", ko: "왼쪽", pos: "명사", exEn: "Turn left at the corner.", exKo: "모퉁이에서 왼쪽으로 도세요.", unit: "u106" },
  { id: "w056", en: "right", ko: "오른쪽", pos: "명사", exEn: "The bank is on your right.", exKo: "은행은 오른쪽에 있어요.", unit: "u106" },
  { id: "w057", en: "near", ko: "가까운", pos: "형용사", exEn: "Is it near here?", exKo: "여기서 가까워요?", unit: "u106" },
  { id: "w058", en: "far", ko: "먼", pos: "형용사", exEn: "It's not far from here.", exKo: "여기서 멀지 않아요.", unit: "u106" },
  { id: "w059", en: "here", ko: "여기", pos: "부사", exEn: "Please sign here.", exKo: "여기에 서명해 주세요.", unit: "u106" },
  { id: "w060", en: "there", ko: "저기", pos: "부사", exEn: "The bus stop is over there.", exKo: "버스 정류장은 저기에 있어요.", unit: "u106" },
  { id: "w061", en: "money", ko: "돈", pos: "명사", exEn: "I don't have much money.", exKo: "돈이 많지 않아요.", unit: "u107" },
  { id: "w062", en: "price", ko: "가격", pos: "명사", exEn: "The price is too high.", exKo: "가격이 너무 비싸요.", unit: "u107" },
  { id: "w063", en: "cheap", ko: "싼, 저렴한", pos: "형용사", exEn: "This shirt is really cheap.", exKo: "이 셔츠는 정말 싸요.", unit: "u107" },
  { id: "w064", en: "expensive", ko: "비싼", pos: "형용사", exEn: "That bag looks expensive.", exKo: "저 가방은 비싸 보여요.", unit: "u107" },
  { id: "w065", en: "sale", ko: "세일, 할인 판매", pos: "명사", exEn: "These shoes are on sale.", exKo: "이 신발은 세일 중이에요.", unit: "u107" },
  { id: "w066", en: "size", ko: "크기, 사이즈", pos: "명사", exEn: "Do you have a bigger size?", exKo: "더 큰 사이즈 있나요?", unit: "u107" },
  { id: "w067", en: "color", ko: "색깔", pos: "명사", exEn: "What color do you like?", exKo: "무슨 색을 좋아하세요?", unit: "u107" },
  { id: "w068", en: "pay", ko: "지불하다", pos: "동사", exEn: "Can I pay by card?", exKo: "카드로 계산해도 되나요?", unit: "u107" },
  { id: "w069", en: "cash", ko: "현금", pos: "명사", exEn: "I'll pay in cash.", exKo: "현금으로 낼게요.", unit: "u107" },
  { id: "w070", en: "receipt", ko: "영수증", pos: "명사", exEn: "Can I get a receipt?", exKo: "영수증 주시겠어요?", unit: "u107" },
  { id: "w071", en: "happy", ko: "행복한", pos: "형용사", exEn: "I'm so happy today.", exKo: "오늘 정말 행복해요.", unit: "u108" },
  { id: "w072", en: "sad", ko: "슬픈", pos: "형용사", exEn: "Why do you look so sad?", exKo: "왜 그렇게 슬퍼 보여요?", unit: "u108" },
  { id: "w073", en: "angry", ko: "화난", pos: "형용사", exEn: "Don't be angry with me.", exKo: "저한테 화내지 마세요.", unit: "u108" },
  { id: "w074", en: "tired", ko: "피곤한", pos: "형용사", exEn: "I'm tired after work.", exKo: "퇴근 후라 피곤해요.", unit: "u108" },
  { id: "w075", en: "busy", ko: "바쁜", pos: "형용사", exEn: "Are you busy this weekend?", exKo: "이번 주말에 바빠요?", unit: "u108" },
  { id: "w076", en: "sick", ko: "아픈", pos: "형용사", exEn: "I feel sick today.", exKo: "오늘 몸이 아파요.", unit: "u108" },
  { id: "w077", en: "fine", ko: "괜찮은", pos: "형용사", exEn: "I'm fine, thanks.", exKo: "저는 괜찮아요, 고마워요.", unit: "u108" },
  { id: "w078", en: "great", ko: "아주 좋은", pos: "형용사", exEn: "That's a great idea!", exKo: "정말 좋은 생각이에요!", unit: "u108" },
  { id: "w079", en: "worried", ko: "걱정하는", pos: "형용사", exEn: "Don't be worried about me.", exKo: "제 걱정은 하지 마세요.", unit: "u108" },
  { id: "w080", en: "excited", ko: "신나는, 들뜬", pos: "형용사", exEn: "I'm excited about the trip.", exKo: "여행 때문에 신나요.", unit: "u108" },

  // ---------- Lv.2 일상 중급 ----------
  { id: "w101", en: "borrow", ko: "빌리다", pos: "동사", exEn: "Can I borrow your charger?", exKo: "충전기 좀 빌릴 수 있을까요?", unit: "u201" },
  { id: "w102", en: "lend", ko: "빌려주다", pos: "동사", exEn: "He lent me an umbrella.", exKo: "그가 우산을 빌려줬어요.", unit: "u201" },
  { id: "w103", en: "fix", ko: "고치다", pos: "동사", exEn: "Can you fix the printer?", exKo: "프린터 좀 고쳐줄 수 있어요?", unit: "u201" },
  { id: "w104", en: "lose", ko: "잃어버리다", pos: "동사", exEn: "I lost my wallet on the bus.", exKo: "버스에서 지갑을 잃어버렸어요.", unit: "u201" },
  { id: "w105", en: "charge", ko: "충전하다", pos: "동사", exEn: "I need to charge my phone.", exKo: "휴대폰을 충전해야 해요.", unit: "u201" },
  { id: "w106", en: "spill", ko: "쏟다", pos: "동사", exEn: "I spilled coffee on my shirt.", exKo: "셔츠에 커피를 쏟았어요.", unit: "u201" },
  { id: "w107", en: "throw away", ko: "버리다", pos: "구동사", exEn: "Don't throw away the receipt.", exKo: "영수증을 버리지 마세요.", unit: "u201" },
  { id: "w108", en: "turn on", ko: "켜다", pos: "구동사", exEn: "Turn on the air conditioner, please.", exKo: "에어컨 좀 켜 주세요.", unit: "u201" },
  { id: "w109", en: "move", ko: "이사하다, 옮기다", pos: "동사", exEn: "We moved to a new apartment last week.", exKo: "지난주에 새 아파트로 이사했어요.", unit: "u201" },
  { id: "w110", en: "invite", ko: "초대하다", pos: "동사", exEn: "She invited me to her housewarming party.", exKo: "그녀가 집들이에 저를 초대했어요.", unit: "u201" },
  { id: "w111", en: "routine", ko: "일과, 습관적인 일", pos: "명사", exEn: "Exercise is part of my daily routine.", exKo: "운동은 제 하루 일과 중 하나예요.", unit: "u202" },
  { id: "w112", en: "commute", ko: "통근하다", pos: "동사", exEn: "I commute by subway every day.", exKo: "저는 매일 지하철로 통근해요.", unit: "u202" },
  { id: "w113", en: "oversleep", ko: "늦잠 자다", pos: "동사", exEn: "I overslept and missed the bus.", exKo: "늦잠 자서 버스를 놓쳤어요.", unit: "u202" },
  { id: "w114", en: "errand", ko: "볼일, 심부름", pos: "명사", exEn: "I have some errands to run today.", exKo: "오늘 볼일이 좀 있어요.", unit: "u202" },
  { id: "w115", en: "chore", ko: "집안일", pos: "명사", exEn: "Doing chores takes a lot of time.", exKo: "집안일은 시간이 많이 걸려요.", unit: "u202" },
  { id: "w116", en: "laundry", ko: "빨래", pos: "명사", exEn: "I do the laundry on weekends.", exKo: "저는 주말에 빨래를 해요.", unit: "u202" },
  { id: "w117", en: "appointment", ko: "약속, 예약", pos: "명사", exEn: "I have a dentist appointment at three.", exKo: "3시에 치과 예약이 있어요.", unit: "u202" },
  { id: "w118", en: "nap", ko: "낮잠", pos: "명사", exEn: "I took a short nap after lunch.", exKo: "점심 먹고 잠깐 낮잠을 잤어요.", unit: "u202" },
  { id: "w119", en: "organize", ko: "정리하다", pos: "동사", exEn: "I need to organize my desk.", exKo: "책상을 정리해야 해요.", unit: "u202" },
  { id: "w120", en: "schedule", ko: "일정", pos: "명사", exEn: "My schedule is full this week.", exKo: "이번 주 일정이 꽉 찼어요.", unit: "u202" },
  { id: "w121", en: "relationship", ko: "관계", pos: "명사", exEn: "They have a good relationship.", exKo: "그들은 사이가 좋아요.", unit: "u203" },
  { id: "w122", en: "personality", ko: "성격", pos: "명사", exEn: "She has a bright personality.", exKo: "그녀는 밝은 성격이에요.", unit: "u203" },
  { id: "w123", en: "trust", ko: "신뢰하다", pos: "동사", exEn: "I trust my best friend completely.", exKo: "저는 제일 친한 친구를 완전히 믿어요.", unit: "u203" },
  { id: "w124", en: "argue", ko: "말다툼하다", pos: "동사", exEn: "They argue about small things.", exKo: "그들은 사소한 일로 다퉈요.", unit: "u203" },
  { id: "w125", en: "apologize", ko: "사과하다", pos: "동사", exEn: "You should apologize to her.", exKo: "그녀에게 사과해야 해요.", unit: "u203" },
  { id: "w126", en: "forgive", ko: "용서하다", pos: "동사", exEn: "I forgave him for being late.", exKo: "늦은 것에 대해 그를 용서했어요.", unit: "u203" },
  { id: "w127", en: "respect", ko: "존중하다", pos: "동사", exEn: "We should respect each other.", exKo: "우리는 서로 존중해야 해요.", unit: "u203" },
  { id: "w128", en: "promise", ko: "약속하다", pos: "동사", exEn: "I promise I won't be late again.", exKo: "다시는 늦지 않겠다고 약속할게요.", unit: "u203" },
  { id: "w129", en: "get along", ko: "잘 지내다", pos: "구동사", exEn: "I get along well with my coworkers.", exKo: "저는 동료들과 잘 지내요.", unit: "u203" },
  { id: "w130", en: "hang out", ko: "어울려 놀다", pos: "구동사", exEn: "We hung out at the mall yesterday.", exKo: "우리는 어제 쇼핑몰에서 놀았어요.", unit: "u203" },
  { id: "w131", en: "nervous", ko: "긴장한", pos: "형용사", exEn: "I was nervous before the interview.", exKo: "면접 전에 긴장했어요.", unit: "u204" },
  { id: "w132", en: "embarrassed", ko: "창피한", pos: "형용사", exEn: "I felt embarrassed about my mistake.", exKo: "제 실수가 창피했어요.", unit: "u204" },
  { id: "w133", en: "disappointed", ko: "실망한", pos: "형용사", exEn: "He was disappointed with the result.", exKo: "그는 결과에 실망했어요.", unit: "u204" },
  { id: "w134", en: "jealous", ko: "질투하는", pos: "형용사", exEn: "She felt jealous of her friend.", exKo: "그녀는 친구를 질투했어요.", unit: "u204" },
  { id: "w135", en: "proud", ko: "자랑스러운", pos: "형용사", exEn: "I'm proud of you.", exKo: "네가 자랑스러워.", unit: "u204" },
  { id: "w136", en: "confident", ko: "자신감 있는", pos: "형용사", exEn: "Be confident in yourself.", exKo: "자신감을 가지세요.", unit: "u204" },
  { id: "w137", en: "annoyed", ko: "짜증 난", pos: "형용사", exEn: "I was annoyed by the loud music.", exKo: "시끄러운 음악 때문에 짜증 났어요.", unit: "u204" },
  { id: "w138", en: "relieved", ko: "안도한", pos: "형용사", exEn: "I was relieved to hear the news.", exKo: "그 소식을 듣고 안심했어요.", unit: "u204" },
  { id: "w139", en: "frustrated", ko: "답답한, 좌절한", pos: "형용사", exEn: "I get frustrated when I can't express myself.", exKo: "제 생각을 표현 못 하면 답답해요.", unit: "u204" },
  { id: "w140", en: "grateful", ko: "감사하는", pos: "형용사", exEn: "I'm grateful for your support.", exKo: "당신의 응원에 감사해요.", unit: "u204" },
  { id: "w141", en: "recipe", ko: "조리법", pos: "명사", exEn: "This recipe is easy to follow.", exKo: "이 조리법은 따라 하기 쉬워요.", unit: "u205" },
  { id: "w142", en: "ingredient", ko: "재료", pos: "명사", exEn: "Mix all the ingredients in a bowl.", exKo: "모든 재료를 그릇에 섞으세요.", unit: "u205" },
  { id: "w143", en: "boil", ko: "끓이다", pos: "동사", exEn: "Boil the water first.", exKo: "먼저 물을 끓이세요.", unit: "u205" },
  { id: "w144", en: "fry", ko: "튀기다, 볶다", pos: "동사", exEn: "Fry the onions until golden.", exKo: "양파를 노릇해질 때까지 볶으세요.", unit: "u205" },
  { id: "w145", en: "flavor", ko: "맛, 풍미", pos: "명사", exEn: "This ice cream has a rich flavor.", exKo: "이 아이스크림은 맛이 진해요.", unit: "u205" },
  { id: "w146", en: "spicy", ko: "매운", pos: "형용사", exEn: "Korean food is often spicy.", exKo: "한국 음식은 매운 경우가 많아요.", unit: "u205" },
  { id: "w147", en: "sour", ko: "신, 시큼한", pos: "형용사", exEn: "This lemon is too sour.", exKo: "이 레몬은 너무 셔요.", unit: "u205" },
  { id: "w148", en: "bitter", ko: "쓴", pos: "형용사", exEn: "The coffee tastes bitter.", exKo: "이 커피는 쓴맛이 나요.", unit: "u205" },
  { id: "w149", en: "order", ko: "주문하다", pos: "동사", exEn: "Are you ready to order?", exKo: "주문하시겠어요?", unit: "u205" },
  { id: "w150", en: "leftover", ko: "남은 음식", pos: "명사", exEn: "We had leftovers for dinner.", exKo: "저녁으로 남은 음식을 먹었어요.", unit: "u205" },
  { id: "w151", en: "healthy", ko: "건강한", pos: "형용사", exEn: "Eating vegetables keeps you healthy.", exKo: "채소를 먹으면 건강해져요.", unit: "u206" },
  { id: "w152", en: "muscle", ko: "근육", pos: "명사", exEn: "My muscles are sore from the gym.", exKo: "헬스장 다녀와서 근육이 아파요.", unit: "u206" },
  { id: "w153", en: "stretch", ko: "스트레칭하다, 늘이다", pos: "동사", exEn: "Stretch before you exercise.", exKo: "운동 전에 스트레칭하세요.", unit: "u206" },
  { id: "w154", en: "sweat", ko: "땀을 흘리다", pos: "동사", exEn: "I sweat a lot when I run.", exKo: "달리면 땀이 많이 나요.", unit: "u206" },
  { id: "w155", en: "diet", ko: "식단, 다이어트", pos: "명사", exEn: "A balanced diet is important.", exKo: "균형 잡힌 식단이 중요해요.", unit: "u206" },
  { id: "w156", en: "injury", ko: "부상", pos: "명사", exEn: "He missed the game because of an injury.", exKo: "그는 부상 때문에 경기에 못 나갔어요.", unit: "u206" },
  { id: "w157", en: "recover", ko: "회복하다", pos: "동사", exEn: "It took a week to recover from the cold.", exKo: "감기가 낫는 데 일주일 걸렸어요.", unit: "u206" },
  { id: "w158", en: "energy", ko: "에너지, 기운", pos: "명사", exEn: "I have no energy today.", exKo: "오늘은 기운이 없어요.", unit: "u206" },
  { id: "w159", en: "habit", ko: "습관", pos: "명사", exEn: "Reading before bed is a good habit.", exKo: "자기 전 독서는 좋은 습관이에요.", unit: "u206" },
  { id: "w160", en: "regularly", ko: "규칙적으로", pos: "부사", exEn: "I exercise regularly.", exKo: "저는 규칙적으로 운동해요.", unit: "u206" },
  { id: "w161", en: "afford", ko: "(살) 여유가 되다", pos: "동사", exEn: "I can't afford a new car.", exKo: "새 차를 살 여유가 없어요.", unit: "u207" },
  { id: "w162", en: "refund", ko: "환불", pos: "명사", exEn: "Can I get a refund for this?", exKo: "이거 환불받을 수 있나요?", unit: "u207" },
  { id: "w163", en: "exchange", ko: "교환하다", pos: "동사", exEn: "I'd like to exchange this for a bigger one.", exKo: "이것을 더 큰 것으로 교환하고 싶어요.", unit: "u207" },
  { id: "w164", en: "quality", ko: "품질", pos: "명사", exEn: "The quality of this jacket is great.", exKo: "이 재킷은 품질이 좋아요.", unit: "u207" },
  { id: "w165", en: "discount", ko: "할인", pos: "명사", exEn: "Is there a discount for students?", exKo: "학생 할인이 있나요?", unit: "u207" },
  { id: "w166", en: "deliver", ko: "배달하다", pos: "동사", exEn: "They deliver for free.", exKo: "무료로 배달해 줘요.", unit: "u207" },
  { id: "w167", en: "wrap", ko: "포장하다", pos: "동사", exEn: "Could you wrap it as a gift?", exKo: "선물용으로 포장해 주시겠어요?", unit: "u207" },
  { id: "w168", en: "compare", ko: "비교하다", pos: "동사", exEn: "Compare prices before you buy.", exKo: "사기 전에 가격을 비교하세요.", unit: "u207" },
  { id: "w169", en: "bargain", ko: "싸게 산 물건, 흥정", pos: "명사", exEn: "This coat was a real bargain.", exKo: "이 코트는 정말 싸게 잘 샀어요.", unit: "u207" },
  { id: "w170", en: "brand", ko: "상표, 브랜드", pos: "명사", exEn: "I don't care about brands.", exKo: "저는 브랜드는 신경 안 써요.", unit: "u207" },
  { id: "w171", en: "destination", ko: "목적지", pos: "명사", exEn: "We finally arrived at our destination.", exKo: "마침내 목적지에 도착했어요.", unit: "u208" },
  { id: "w172", en: "luggage", ko: "짐, 수하물", pos: "명사", exEn: "My luggage is too heavy.", exKo: "제 짐이 너무 무거워요.", unit: "u208" },
  { id: "w173", en: "reserve", ko: "예약하다", pos: "동사", exEn: "I reserved a table for two.", exKo: "2인용 테이블을 예약했어요.", unit: "u208" },
  { id: "w174", en: "delay", ko: "지연, 지연시키다", pos: "명사/동사", exEn: "The flight was delayed by an hour.", exKo: "비행기가 한 시간 지연됐어요.", unit: "u208" },
  { id: "w175", en: "transfer", ko: "환승하다, 옮기다", pos: "동사", exEn: "Transfer to Line 2 at City Hall.", exKo: "시청에서 2호선으로 갈아타세요.", unit: "u208" },
  { id: "w176", en: "passenger", ko: "승객", pos: "명사", exEn: "The bus was full of passengers.", exKo: "버스가 승객으로 가득했어요.", unit: "u208" },
  { id: "w177", en: "sightseeing", ko: "관광", pos: "명사", exEn: "We went sightseeing in Busan.", exKo: "우리는 부산에서 관광을 했어요.", unit: "u208" },
  { id: "w178", en: "souvenir", ko: "기념품", pos: "명사", exEn: "I bought souvenirs for my friends.", exKo: "친구들에게 줄 기념품을 샀어요.", unit: "u208" },
  { id: "w179", en: "departure", ko: "출발", pos: "명사", exEn: "Check the departure time again.", exKo: "출발 시간을 다시 확인하세요.", unit: "u208" },
  { id: "w180", en: "arrive", ko: "도착하다", pos: "동사", exEn: "What time does the train arrive?", exKo: "기차가 몇 시에 도착해요?", unit: "u208" },
  { id: "w181", en: "forecast", ko: "일기예보", pos: "명사", exEn: "The forecast says it will rain tomorrow.", exKo: "일기예보에서 내일 비가 온대요.", unit: "u209" },
  { id: "w182", en: "humid", ko: "습한", pos: "형용사", exEn: "Summer in Korea is hot and humid.", exKo: "한국의 여름은 덥고 습해요.", unit: "u209" },
  { id: "w183", en: "freezing", ko: "몹시 추운", pos: "형용사", exEn: "It's freezing outside!", exKo: "밖이 얼어붙을 듯이 추워요!", unit: "u209" },
  { id: "w184", en: "breeze", ko: "산들바람", pos: "명사", exEn: "A cool breeze came through the window.", exKo: "창문으로 시원한 바람이 들어왔어요.", unit: "u209" },
  { id: "w185", en: "thunder", ko: "천둥", pos: "명사", exEn: "The thunder scared my dog.", exKo: "천둥소리에 우리 개가 놀랐어요.", unit: "u209" },
  { id: "w186", en: "temperature", ko: "온도, 기온", pos: "명사", exEn: "The temperature dropped suddenly.", exKo: "기온이 갑자기 떨어졌어요.", unit: "u209" },
  { id: "w187", en: "pollution", ko: "오염", pos: "명사", exEn: "Air pollution is getting worse.", exKo: "대기 오염이 점점 심해지고 있어요.", unit: "u209" },
  { id: "w188", en: "environment", ko: "환경", pos: "명사", exEn: "We should protect the environment.", exKo: "우리는 환경을 보호해야 해요.", unit: "u209" },
  { id: "w189", en: "season", ko: "계절", pos: "명사", exEn: "Which season do you like best?", exKo: "어느 계절을 제일 좋아해요?", unit: "u209" },
  { id: "w190", en: "shade", ko: "그늘", pos: "명사", exEn: "Let's rest in the shade.", exKo: "그늘에서 쉬어요.", unit: "u209" },
  { id: "w191", en: "opinion", ko: "의견", pos: "명사", exEn: "In my opinion, it's worth trying.", exKo: "제 생각에는 시도해 볼 만해요.", unit: "u210" },
  { id: "w192", en: "agree", ko: "동의하다", pos: "동사", exEn: "I agree with your idea.", exKo: "당신 생각에 동의해요.", unit: "u210" },
  { id: "w193", en: "disagree", ko: "동의하지 않다", pos: "동사", exEn: "I'm sorry, but I disagree.", exKo: "미안하지만 저는 생각이 달라요.", unit: "u210" },
  { id: "w194", en: "suggest", ko: "제안하다", pos: "동사", exEn: "I suggest taking a break.", exKo: "잠깐 쉬는 걸 제안해요.", unit: "u210" },
  { id: "w195", en: "explain", ko: "설명하다", pos: "동사", exEn: "Can you explain it again?", exKo: "다시 설명해 주시겠어요?", unit: "u210" },
  { id: "w196", en: "describe", ko: "묘사하다", pos: "동사", exEn: "Describe the person you saw.", exKo: "당신이 본 사람을 묘사해 보세요.", unit: "u210" },
  { id: "w197", en: "mention", ko: "언급하다", pos: "동사", exEn: "He mentioned your name yesterday.", exKo: "그가 어제 당신 이름을 언급했어요.", unit: "u210" },
  { id: "w198", en: "discuss", ko: "논의하다", pos: "동사", exEn: "Let's discuss this over lunch.", exKo: "점심 먹으면서 이 문제를 논의해요.", unit: "u210" },
  { id: "w199", en: "persuade", ko: "설득하다", pos: "동사", exEn: "She persuaded me to join the club.", exKo: "그녀가 저를 동아리에 가입하라고 설득했어요.", unit: "u210" },
  { id: "w200", en: "misunderstand", ko: "오해하다", pos: "동사", exEn: "Don't misunderstand me.", exKo: "오해하지 마세요.", unit: "u210" },

  // ---------- Lv.3 일상 고급 ----------
  { id: "w301", en: "colleague", ko: "동료", pos: "명사", exEn: "I had lunch with my colleagues.", exKo: "동료들과 점심을 먹었어요.", unit: "u301" },
  { id: "w302", en: "deadline", ko: "마감일", pos: "명사", exEn: "The deadline is this Friday.", exKo: "마감일이 이번 주 금요일이에요.", unit: "u301" },
  { id: "w303", en: "negotiate", ko: "협상하다", pos: "동사", exEn: "We negotiated the price.", exKo: "우리는 가격을 협상했어요.", unit: "u301" },
  { id: "w304", en: "promotion", ko: "승진", pos: "명사", exEn: "She got a promotion last month.", exKo: "그녀는 지난달에 승진했어요.", unit: "u301" },
  { id: "w305", en: "resign", ko: "사직하다", pos: "동사", exEn: "He resigned from his job.", exKo: "그는 회사를 그만뒀어요.", unit: "u301" },
  { id: "w306", en: "overtime", ko: "야근, 초과 근무", pos: "명사", exEn: "I worked overtime all week.", exKo: "일주일 내내 야근했어요.", unit: "u301" },
  { id: "w307", en: "workload", ko: "업무량", pos: "명사", exEn: "My workload has doubled recently.", exKo: "최근에 업무량이 두 배가 됐어요.", unit: "u301" },
  { id: "w308", en: "achievement", ko: "성과, 업적", pos: "명사", exEn: "Winning the award was a great achievement.", exKo: "그 상을 받은 건 큰 성과였어요.", unit: "u301" },
  { id: "w309", en: "efficient", ko: "효율적인", pos: "형용사", exEn: "This is a more efficient way to work.", exKo: "이게 더 효율적인 업무 방식이에요.", unit: "u301" },
  { id: "w310", en: "responsibility", ko: "책임", pos: "명사", exEn: "It's my responsibility to finish this.", exKo: "이걸 끝내는 건 제 책임이에요.", unit: "u301" },
  { id: "w311", en: "budget", ko: "예산", pos: "명사", exEn: "We're on a tight budget this month.", exKo: "이번 달은 예산이 빠듯해요.", unit: "u302" },
  { id: "w312", en: "income", ko: "수입", pos: "명사", exEn: "His income increased this year.", exKo: "올해 그의 수입이 늘었어요.", unit: "u302" },
  { id: "w313", en: "expense", ko: "지출, 비용", pos: "명사", exEn: "Living expenses keep rising.", exKo: "생활비가 계속 오르고 있어요.", unit: "u302" },
  { id: "w314", en: "invest", ko: "투자하다", pos: "동사", exEn: "She invests in stocks.", exKo: "그녀는 주식에 투자해요.", unit: "u302" },
  { id: "w315", en: "savings", ko: "저축, 모아둔 돈", pos: "명사", exEn: "I used my savings to buy a laptop.", exKo: "노트북을 사려고 모아둔 돈을 썼어요.", unit: "u302" },
  { id: "w316", en: "debt", ko: "빚", pos: "명사", exEn: "He finally paid off his debt.", exKo: "그는 마침내 빚을 다 갚았어요.", unit: "u302" },
  { id: "w317", en: "insurance", ko: "보험", pos: "명사", exEn: "Do you have travel insurance?", exKo: "여행자 보험 있으세요?", unit: "u302" },
  { id: "w318", en: "tax", ko: "세금", pos: "명사", exEn: "The price includes tax.", exKo: "그 가격은 세금 포함이에요.", unit: "u302" },
  { id: "w319", en: "worth", ko: "~의 가치가 있는", pos: "형용사", exEn: "This movie is worth watching.", exKo: "이 영화는 볼 가치가 있어요.", unit: "u302" },
  { id: "w320", en: "economy", ko: "경제", pos: "명사", exEn: "The economy is slowly recovering.", exKo: "경제가 서서히 회복되고 있어요.", unit: "u302" },
  { id: "w321", en: "government", ko: "정부", pos: "명사", exEn: "The government announced a new policy.", exKo: "정부가 새 정책을 발표했어요.", unit: "u303" },
  { id: "w322", en: "policy", ko: "정책", pos: "명사", exEn: "What do you think of this policy?", exKo: "이 정책에 대해 어떻게 생각해요?", unit: "u303" },
  { id: "w323", en: "election", ko: "선거", pos: "명사", exEn: "The election is next month.", exKo: "선거가 다음 달이에요.", unit: "u303" },
  { id: "w324", en: "citizen", ko: "시민", pos: "명사", exEn: "Every citizen has the right to vote.", exKo: "모든 시민은 투표할 권리가 있어요.", unit: "u303" },
  { id: "w325", en: "crime", ko: "범죄", pos: "명사", exEn: "The crime rate has dropped.", exKo: "범죄율이 떨어졌어요.", unit: "u303" },
  { id: "w326", en: "evidence", ko: "증거", pos: "명사", exEn: "There is no evidence for that claim.", exKo: "그 주장에는 증거가 없어요.", unit: "u303" },
  { id: "w327", en: "protest", ko: "시위", pos: "명사", exEn: "People joined the protest downtown.", exKo: "사람들이 시내 시위에 참여했어요.", unit: "u303" },
  { id: "w328", en: "issue", ko: "쟁점, 문제", pos: "명사", exEn: "Housing is a serious issue now.", exKo: "주거 문제가 지금 심각한 쟁점이에요.", unit: "u303" },
  { id: "w329", en: "public", ko: "대중의, 공공의", pos: "형용사", exEn: "This park is open to the public.", exKo: "이 공원은 대중에게 개방돼 있어요.", unit: "u303" },
  { id: "w330", en: "media", ko: "언론, 미디어", pos: "명사", exEn: "The story spread quickly through the media.", exKo: "그 이야기는 언론을 통해 빠르게 퍼졌어요.", unit: "u303" },
  { id: "w331", en: "generous", ko: "관대한, 후한", pos: "형용사", exEn: "She is generous with her time.", exKo: "그녀는 시간을 아끼지 않고 베풀어요.", unit: "u304" },
  { id: "w332", en: "stubborn", ko: "고집 센", pos: "형용사", exEn: "He's too stubborn to change his mind.", exKo: "그는 고집이 세서 생각을 안 바꿔요.", unit: "u304" },
  { id: "w333", en: "polite", ko: "예의 바른", pos: "형용사", exEn: "The staff were very polite.", exKo: "직원들이 매우 예의 발랐어요.", unit: "u304" },
  { id: "w334", en: "honest", ko: "정직한, 솔직한", pos: "형용사", exEn: "To be honest, I don't like it.", exKo: "솔직히 말하면 마음에 안 들어요.", unit: "u304" },
  { id: "w335", en: "ambitious", ko: "야심 있는", pos: "형용사", exEn: "She's ambitious about her career.", exKo: "그녀는 커리어에 야심이 있어요.", unit: "u304" },
  { id: "w336", en: "humble", ko: "겸손한", pos: "형용사", exEn: "He stays humble despite his success.", exKo: "그는 성공했는데도 겸손해요.", unit: "u304" },
  { id: "w337", en: "sensitive", ko: "예민한, 세심한", pos: "형용사", exEn: "She's sensitive to criticism.", exKo: "그녀는 비판에 예민해요.", unit: "u304" },
  { id: "w338", en: "reliable", ko: "믿을 수 있는", pos: "형용사", exEn: "He's a reliable person.", exKo: "그는 믿을 수 있는 사람이에요.", unit: "u304" },
  { id: "w339", en: "curious", ko: "호기심 많은", pos: "형용사", exEn: "Children are naturally curious.", exKo: "아이들은 원래 호기심이 많아요.", unit: "u304" },
  { id: "w340", en: "patient", ko: "참을성 있는", pos: "형용사", exEn: "Be patient. It takes time.", exKo: "인내심을 가지세요. 시간이 걸려요.", unit: "u304" },
  { id: "w341", en: "postpone", ko: "연기하다", pos: "동사", exEn: "The meeting was postponed to Monday.", exKo: "회의가 월요일로 연기됐어요.", unit: "u305" },
  { id: "w342", en: "cancel", ko: "취소하다", pos: "동사", exEn: "I had to cancel my trip.", exKo: "여행을 취소해야 했어요.", unit: "u305" },
  { id: "w343", en: "gradually", ko: "서서히", pos: "부사", exEn: "Things are gradually getting better.", exKo: "상황이 서서히 나아지고 있어요.", unit: "u305" },
  { id: "w344", en: "immediately", ko: "즉시", pos: "부사", exEn: "Please reply immediately.", exKo: "즉시 답장해 주세요.", unit: "u305" },
  { id: "w345", en: "occasionally", ko: "가끔", pos: "부사", exEn: "I occasionally eat out.", exKo: "저는 가끔 외식해요.", unit: "u305" },
  { id: "w346", en: "temporary", ko: "일시적인", pos: "형용사", exEn: "This is just a temporary problem.", exKo: "이건 일시적인 문제일 뿐이에요.", unit: "u305" },
  { id: "w347", en: "permanent", ko: "영구적인, 정규의", pos: "형용사", exEn: "She got a permanent position.", exKo: "그녀는 정규직 자리를 얻었어요.", unit: "u305" },
  { id: "w348", en: "urgent", ko: "긴급한", pos: "형용사", exEn: "I have an urgent message for you.", exKo: "급한 전할 말이 있어요.", unit: "u305" },
  { id: "w349", en: "previous", ko: "이전의", pos: "형용사", exEn: "My previous job was more stressful.", exKo: "이전 직장이 더 스트레스가 심했어요.", unit: "u305" },
  { id: "w350", en: "eventually", ko: "결국", pos: "부사", exEn: "Eventually, everything worked out.", exKo: "결국 모든 일이 잘 풀렸어요.", unit: "u305" },
  { id: "w351", en: "solution", ko: "해결책", pos: "명사", exEn: "We need a better solution.", exKo: "더 나은 해결책이 필요해요.", unit: "u306" },
  { id: "w352", en: "cause", ko: "원인", pos: "명사", exEn: "What was the cause of the delay?", exKo: "지연의 원인이 뭐였어요?", unit: "u306" },
  { id: "w353", en: "prevent", ko: "예방하다", pos: "동사", exEn: "Washing hands prevents illness.", exKo: "손 씻기는 병을 예방해요.", unit: "u306" },
  { id: "w354", en: "avoid", ko: "피하다", pos: "동사", exEn: "I avoid driving during rush hour.", exKo: "저는 러시아워에는 운전을 피해요.", unit: "u306" },
  { id: "w355", en: "improve", ko: "개선하다, 향상시키다", pos: "동사", exEn: "I want to improve my English.", exKo: "영어 실력을 향상시키고 싶어요.", unit: "u306" },
  { id: "w356", en: "complain", ko: "불평하다", pos: "동사", exEn: "He complained about the service.", exKo: "그는 서비스에 대해 불평했어요.", unit: "u306" },
  { id: "w357", en: "handle", ko: "처리하다, 다루다", pos: "동사", exEn: "She handled the situation well.", exKo: "그녀는 상황을 잘 처리했어요.", unit: "u306" },
  { id: "w358", en: "struggle", ko: "고군분투하다", pos: "동사", exEn: "I'm struggling with this project.", exKo: "이 프로젝트 때문에 애먹고 있어요.", unit: "u306" },
  { id: "w359", en: "overcome", ko: "극복하다", pos: "동사", exEn: "He overcame his fear of speaking.", exKo: "그는 말하기 공포를 극복했어요.", unit: "u306" },
  { id: "w360", en: "effect", ko: "효과, 영향", pos: "명사", exEn: "The medicine had an immediate effect.", exKo: "그 약은 즉각 효과가 있었어요.", unit: "u306" },
  { id: "w361", en: "give up", ko: "포기하다", pos: "구동사", exEn: "Don't give up on your dream.", exKo: "꿈을 포기하지 마세요.", unit: "u307" },
  { id: "w362", en: "look forward to", ko: "~을 기대하다", pos: "구동사", exEn: "I look forward to seeing you.", exKo: "만나 뵙기를 기대해요.", unit: "u307" },
  { id: "w363", en: "run out of", ko: "~이 다 떨어지다", pos: "구동사", exEn: "We ran out of milk.", exKo: "우유가 다 떨어졌어요.", unit: "u307" },
  { id: "w364", en: "put off", ko: "미루다", pos: "구동사", exEn: "Stop putting off your homework.", exKo: "숙제 그만 미루세요.", unit: "u307" },
  { id: "w365", en: "figure out", ko: "알아내다, 이해하다", pos: "구동사", exEn: "I can't figure out this problem.", exKo: "이 문제를 못 풀겠어요.", unit: "u307" },
  { id: "w366", en: "come up with", ko: "(아이디어를) 떠올리다", pos: "구동사", exEn: "She came up with a great idea.", exKo: "그녀가 좋은 아이디어를 떠올렸어요.", unit: "u307" },
  { id: "w367", en: "deal with", ko: "처리하다, 다루다", pos: "구동사", exEn: "I'll deal with it tomorrow.", exKo: "내일 처리할게요.", unit: "u307" },
  { id: "w368", en: "take care of", ko: "돌보다", pos: "구동사", exEn: "Who takes care of your dog?", exKo: "누가 당신 개를 돌봐요?", unit: "u307" },
  { id: "w369", en: "get used to", ko: "~에 익숙해지다", pos: "구동사", exEn: "I got used to waking up early.", exKo: "일찍 일어나는 데 익숙해졌어요.", unit: "u307" },
  { id: "w370", en: "break down", ko: "고장 나다", pos: "구동사", exEn: "My car broke down on the highway.", exKo: "고속도로에서 차가 고장 났어요.", unit: "u307" },
  { id: "w371", en: "overwhelmed", ko: "압도된, 감당이 안 되는", pos: "형용사", exEn: "I felt overwhelmed by all the work.", exKo: "일이 너무 많아서 감당이 안 됐어요.", unit: "u308" },
  { id: "w372", en: "anxious", ko: "불안한", pos: "형용사", exEn: "She feels anxious before exams.", exKo: "그녀는 시험 전에 불안해해요.", unit: "u308" },
  { id: "w373", en: "awkward", ko: "어색한", pos: "형용사", exEn: "There was an awkward silence.", exKo: "어색한 침묵이 흘렀어요.", unit: "u308" },
  { id: "w374", en: "exhausted", ko: "기진맥진한", pos: "형용사", exEn: "I was exhausted after the trip.", exKo: "여행 후에 완전히 지쳤어요.", unit: "u308" },
  { id: "w375", en: "motivated", ko: "의욕적인", pos: "형용사", exEn: "I feel motivated to study today.", exKo: "오늘은 공부할 의욕이 생겨요.", unit: "u308" },
  { id: "w376", en: "hesitant", ko: "주저하는", pos: "형용사", exEn: "He was hesitant to ask for help.", exKo: "그는 도움을 청하기를 주저했어요.", unit: "u308" },
  { id: "w377", en: "indifferent", ko: "무관심한", pos: "형용사", exEn: "She seemed indifferent to the news.", exKo: "그녀는 그 소식에 무관심해 보였어요.", unit: "u308" },
  { id: "w378", en: "sympathetic", ko: "공감하는, 동정적인", pos: "형용사", exEn: "He gave me a sympathetic look.", exKo: "그는 저를 안쓰럽게 바라봤어요.", unit: "u308" },
  { id: "w379", en: "optimistic", ko: "낙관적인", pos: "형용사", exEn: "I'm optimistic about the future.", exKo: "저는 미래에 대해 낙관적이에요.", unit: "u308" },
  { id: "w380", en: "content", ko: "만족하는", pos: "형용사", exEn: "She is content with her simple life.", exKo: "그녀는 소박한 삶에 만족해요.", unit: "u308" },
];
