// ============================================================
// 확장 단어 팩 1 — 미국 일상 회화 빈도 기반 200단어
// 선별 기준: wordfreq(SUBTLEX-US·OpenSubtitles 등 미국 구어 코퍼스 통합) 빈도 순위
//           + NGSL(학습용 검증 목록) 교차 확인
// ============================================================

[].push.apply(UNITS, [
  { id: "u220", level: "lv2", title: "코어 동사 1" },
  { id: "u221", level: "lv2", title: "코어 동사 2" },
  { id: "u222", level: "lv2", title: "시간·빈도 표현" },
  { id: "u223", level: "lv2", title: "집 안 물건" },
  { id: "u224", level: "lv2", title: "몸이 아플 때" },
  { id: "u225", level: "lv2", title: "전화와 연락" },
  { id: "u226", level: "lv2", title: "모임과 축하" },
  { id: "u227", level: "lv2", title: "교통과 운전" },
  { id: "u228", level: "lv2", title: "돈 쓰는 일상" },
  { id: "u229", level: "lv2", title: "리액션 표현" },
  { id: "u320", level: "lv3", title: "필수 구동사 2" },
  { id: "u321", level: "lv3", title: "미국식 캐주얼 표현" },
  { id: "u322", level: "lv3", title: "생각과 판단" },
  { id: "u323", level: "lv3", title: "감정 고급 2" },
  { id: "u324", level: "lv3", title: "직장 생활 2" },
  { id: "u325", level: "lv3", title: "온라인 쇼핑" },
  { id: "u326", level: "lv3", title: "병원과 운동" },
  { id: "u327", level: "lv3", title: "관계의 기술" },
  { id: "u328", level: "lv3", title: "사회와 공동체" },
  { id: "u329", level: "lv3", title: "계획과 목표" },
]);

[].push.apply(WORDS, [
  // u220 코어 동사 1
  { id: "w401", en: "bring", ko: "가져오다, 데려오다", pos: "동사", exEn: "Can you bring your laptop tomorrow?", exKo: "내일 노트북 좀 가져올 수 있어요?", unit: "u220" },
  { id: "w402", en: "take", ko: "가져가다, (시간이) 걸리다", pos: "동사", exEn: "It takes twenty minutes by bus.", exKo: "버스로 20분 걸려요.", unit: "u220" },
  { id: "w403", en: "keep", ko: "유지하다, 계속하다", pos: "동사", exEn: "Keep the change.", exKo: "잔돈은 가지세요.", unit: "u220" },
  { id: "w404", en: "leave", ko: "떠나다, 두고 오다", pos: "동사", exEn: "I left my phone at home.", exKo: "휴대폰을 집에 두고 왔어요.", unit: "u220" },
  { id: "w405", en: "meet", ko: "만나다", pos: "동사", exEn: "Let's meet in front of the station.", exKo: "역 앞에서 만나요.", unit: "u220" },
  { id: "w406", en: "wait", ko: "기다리다", pos: "동사", exEn: "Sorry to keep you waiting.", exKo: "기다리게 해서 미안해요.", unit: "u220" },
  { id: "w407", en: "call", ko: "전화하다, 부르다", pos: "동사", exEn: "Call me when you get there.", exKo: "도착하면 전화해요.", unit: "u220" },
  { id: "w408", en: "ask", ko: "묻다, 부탁하다", pos: "동사", exEn: "Can I ask you a favor?", exKo: "부탁 하나 해도 될까요?", unit: "u220" },
  { id: "w409", en: "answer", ko: "대답하다, 받다", pos: "동사", exEn: "He didn't answer my call.", exKo: "그가 제 전화를 안 받았어요.", unit: "u220" },
  { id: "w410", en: "need", ko: "필요하다", pos: "동사", exEn: "I need a break.", exKo: "저는 휴식이 필요해요.", unit: "u220" },
  // u221 코어 동사 2
  { id: "w411", en: "try", ko: "시도하다, 먹어 보다", pos: "동사", exEn: "You should try this pizza.", exKo: "이 피자 꼭 먹어 봐요.", unit: "u221" },
  { id: "w412", en: "start", ko: "시작하다", pos: "동사", exEn: "The movie starts at seven.", exKo: "영화는 7시에 시작해요.", unit: "u221" },
  { id: "w413", en: "finish", ko: "끝내다", pos: "동사", exEn: "I just finished my homework.", exKo: "방금 숙제를 끝냈어요.", unit: "u221" },
  { id: "w414", en: "stop", ko: "멈추다, 그만하다", pos: "동사", exEn: "The rain finally stopped.", exKo: "비가 드디어 그쳤어요.", unit: "u221" },
  { id: "w415", en: "stay", ko: "머무르다", pos: "동사", exEn: "How long are you staying?", exKo: "얼마나 머무르실 거예요?", unit: "u221" },
  { id: "w416", en: "visit", ko: "방문하다", pos: "동사", exEn: "We visited my grandma last weekend.", exKo: "지난 주말에 할머니 댁에 다녀왔어요.", unit: "u221" },
  { id: "w417", en: "wear", ko: "입다, 착용하다", pos: "동사", exEn: "What should I wear to the party?", exKo: "파티에 뭘 입고 가지?", unit: "u221" },
  { id: "w418", en: "carry", ko: "들고 다니다, 나르다", pos: "동사", exEn: "Let me carry that bag for you.", exKo: "그 가방 제가 들어 드릴게요.", unit: "u221" },
  { id: "w419", en: "send", ko: "보내다", pos: "동사", exEn: "I'll send you the address.", exKo: "주소 보내 드릴게요.", unit: "u221" },
  { id: "w420", en: "receive", ko: "받다", pos: "동사", exEn: "Did you receive my email?", exKo: "제 이메일 받으셨어요?", unit: "u221" },
  // u222 시간·빈도 표현
  { id: "w421", en: "early", ko: "일찍, 이른", pos: "부사", exEn: "I woke up early this morning.", exKo: "오늘 아침 일찍 일어났어요.", unit: "u222" },
  { id: "w422", en: "late", ko: "늦게, 늦은", pos: "부사", exEn: "Don't stay up too late.", exKo: "너무 늦게까지 깨어 있지 마세요.", unit: "u222" },
  { id: "w423", en: "soon", ko: "곧", pos: "부사", exEn: "See you soon!", exKo: "곧 봐요!", unit: "u222" },
  { id: "w424", en: "already", ko: "이미, 벌써", pos: "부사", exEn: "I already had lunch.", exKo: "점심은 벌써 먹었어요.", unit: "u222" },
  { id: "w425", en: "still", ko: "아직도, 여전히", pos: "부사", exEn: "Are you still at work?", exKo: "아직 회사예요?", unit: "u222" },
  { id: "w426", en: "yet", ko: "아직 (부정문·의문문)", pos: "부사", exEn: "I haven't decided yet.", exKo: "아직 결정 못 했어요.", unit: "u222" },
  { id: "w427", en: "always", ko: "항상", pos: "부사", exEn: "You always make me laugh.", exKo: "넌 항상 날 웃게 해.", unit: "u222" },
  { id: "w428", en: "usually", ko: "보통", pos: "부사", exEn: "I usually get up at seven.", exKo: "저는 보통 7시에 일어나요.", unit: "u222" },
  { id: "w429", en: "sometimes", ko: "가끔", pos: "부사", exEn: "Sometimes I cook dinner myself.", exKo: "가끔은 저녁을 직접 해 먹어요.", unit: "u222" },
  { id: "w430", en: "never", ko: "절대 ~않다", pos: "부사", exEn: "I've never been to New York.", exKo: "뉴욕에 가 본 적이 없어요.", unit: "u222" },
  // u223 집 안 물건
  { id: "w431", en: "kitchen", ko: "부엌", pos: "명사", exEn: "The kitchen smells amazing.", exKo: "부엌에서 좋은 냄새가 나요.", unit: "u223" },
  { id: "w432", en: "bathroom", ko: "화장실, 욕실", pos: "명사", exEn: "Where is the bathroom?", exKo: "화장실이 어디예요?", unit: "u223" },
  { id: "w433", en: "bedroom", ko: "침실", pos: "명사", exEn: "My bedroom is a mess right now.", exKo: "제 침실은 지금 엉망이에요.", unit: "u223" },
  { id: "w434", en: "furniture", ko: "가구", pos: "명사", exEn: "We need new furniture for the living room.", exKo: "거실에 새 가구가 필요해요.", unit: "u223" },
  { id: "w435", en: "refrigerator", ko: "냉장고", pos: "명사", exEn: "There's nothing in the refrigerator.", exKo: "냉장고에 아무것도 없어요.", unit: "u223" },
  { id: "w436", en: "microwave", ko: "전자레인지", pos: "명사", exEn: "Heat it in the microwave for two minutes.", exKo: "전자레인지에 2분 돌리세요.", unit: "u223" },
  { id: "w437", en: "drawer", ko: "서랍", pos: "명사", exEn: "The scissors are in the top drawer.", exKo: "가위는 맨 위 서랍에 있어요.", unit: "u223" },
  { id: "w438", en: "blanket", ko: "이불, 담요", pos: "명사", exEn: "Can I get an extra blanket?", exKo: "담요 하나 더 주시겠어요?", unit: "u223" },
  { id: "w439", en: "pillow", ko: "베개", pos: "명사", exEn: "This pillow is too soft for me.", exKo: "이 베개는 저한테 너무 푹신해요.", unit: "u223" },
  { id: "w440", en: "towel", ko: "수건", pos: "명사", exEn: "Grab a towel from the shelf.", exKo: "선반에서 수건 하나 꺼내요.", unit: "u223" },
  // u224 몸이 아플 때
  { id: "w441", en: "headache", ko: "두통", pos: "명사", exEn: "I have a terrible headache.", exKo: "머리가 너무 아파요.", unit: "u224" },
  { id: "w442", en: "medicine", ko: "약", pos: "명사", exEn: "Take this medicine after meals.", exKo: "이 약은 식후에 드세요.", unit: "u224" },
  { id: "w443", en: "pharmacy", ko: "약국", pos: "명사", exEn: "Is there a pharmacy nearby?", exKo: "근처에 약국이 있나요?", unit: "u224" },
  { id: "w444", en: "dizzy", ko: "어지러운", pos: "형용사", exEn: "I feel dizzy when I stand up.", exKo: "일어설 때 어지러워요.", unit: "u224" },
  { id: "w445", en: "fever", ko: "열", pos: "명사", exEn: "She has a high fever.", exKo: "그녀는 열이 높아요.", unit: "u224" },
  { id: "w446", en: "allergy", ko: "알레르기", pos: "명사", exEn: "I have a pollen allergy.", exKo: "저는 꽃가루 알레르기가 있어요.", unit: "u224" },
  { id: "w447", en: "vitamin", ko: "비타민", pos: "명사", exEn: "I take vitamins every morning.", exKo: "저는 매일 아침 비타민을 먹어요.", unit: "u224" },
  { id: "w448", en: "checkup", ko: "건강 검진", pos: "명사", exEn: "I'm due for my annual checkup.", exKo: "연례 건강 검진 받을 때가 됐어요.", unit: "u224" },
  { id: "w449", en: "flu", ko: "독감", pos: "명사", exEn: "The flu is going around these days.", exKo: "요즘 독감이 유행이에요.", unit: "u224" },
  { id: "w450", en: "cough", ko: "기침", pos: "명사", exEn: "I can't stop coughing.", exKo: "기침이 멈추지 않아요.", unit: "u224" },
  // u225 전화와 연락
  { id: "w451", en: "text", ko: "문자를 보내다", pos: "동사", exEn: "Text me when you're free.", exKo: "시간 되면 문자해요.", unit: "u225" },
  { id: "w452", en: "reply", ko: "답장하다", pos: "동사", exEn: "Sorry for the late reply.", exKo: "답장이 늦어서 미안해요.", unit: "u225" },
  { id: "w453", en: "contact", ko: "연락하다", pos: "동사", exEn: "Feel free to contact me anytime.", exKo: "언제든 편하게 연락하세요.", unit: "u225" },
  { id: "w454", en: "reach", ko: "연락이 닿다", pos: "동사", exEn: "I couldn't reach him all day.", exKo: "하루 종일 그와 연락이 안 됐어요.", unit: "u225" },
  { id: "w455", en: "hang up", ko: "전화를 끊다", pos: "구동사", exEn: "Don't hang up on me!", exKo: "전화 끊지 마!", unit: "u225" },
  { id: "w456", en: "call back", ko: "다시 전화하다", pos: "구동사", exEn: "Can I call you back in ten minutes?", exKo: "10분 뒤에 다시 전화해도 될까요?", unit: "u225" },
  { id: "w457", en: "voicemail", ko: "음성 메시지", pos: "명사", exEn: "I left you a voicemail.", exKo: "음성 메시지 남겼어요.", unit: "u225" },
  { id: "w458", en: "signal", ko: "신호, 수신 상태", pos: "명사", exEn: "The signal is really bad here.", exKo: "여기 수신 상태가 정말 안 좋아요.", unit: "u225" },
  { id: "w459", en: "mute", ko: "음소거하다", pos: "동사", exEn: "You're on mute!", exKo: "음소거 되어 있어요!", unit: "u225" },
  { id: "w460", en: "notification", ko: "알림", pos: "명사", exEn: "I turned off notifications at night.", exKo: "밤에는 알림을 꺼 놔요.", unit: "u225" },
  // u226 모임과 축하
  { id: "w461", en: "party", ko: "파티", pos: "명사", exEn: "Are you coming to the party tonight?", exKo: "오늘 밤 파티에 올 거예요?", unit: "u226" },
  { id: "w462", en: "guest", ko: "손님", pos: "명사", exEn: "We're expecting twenty guests.", exKo: "손님 스무 명이 올 예정이에요.", unit: "u226" },
  { id: "w463", en: "host", ko: "주최하다, 주인", pos: "동사", exEn: "She's hosting a dinner this Saturday.", exKo: "그녀가 이번 토요일에 저녁 모임을 열어요.", unit: "u226" },
  { id: "w464", en: "celebrate", ko: "축하하다, 기념하다", pos: "동사", exEn: "Let's celebrate your new job!", exKo: "새 직장 얻은 거 축하하자!", unit: "u226" },
  { id: "w465", en: "gift", ko: "선물", pos: "명사", exEn: "I got you a little gift.", exKo: "작은 선물 하나 준비했어요.", unit: "u226" },
  { id: "w466", en: "wedding", ko: "결혼식", pos: "명사", exEn: "The wedding is in October.", exKo: "결혼식은 10월이에요.", unit: "u226" },
  { id: "w467", en: "anniversary", ko: "기념일", pos: "명사", exEn: "Today is our fifth anniversary.", exKo: "오늘이 우리 5주년 기념일이에요.", unit: "u226" },
  { id: "w468", en: "congratulate", ko: "축하하다", pos: "동사", exEn: "Everyone congratulated her on the promotion.", exKo: "모두가 그녀의 승진을 축하했어요.", unit: "u226" },
  { id: "w469", en: "invitation", ko: "초대장, 초대", pos: "명사", exEn: "Did you get the invitation?", exKo: "초대장 받았어요?", unit: "u226" },
  { id: "w470", en: "attend", ko: "참석하다", pos: "동사", exEn: "I can't attend the meeting tomorrow.", exKo: "내일 회의에 참석 못 해요.", unit: "u226" },
  // u227 교통과 운전
  { id: "w471", en: "traffic", ko: "교통량, 차 막힘", pos: "명사", exEn: "The traffic is terrible this morning.", exKo: "오늘 아침 차가 너무 막혀요.", unit: "u227" },
  { id: "w472", en: "license", ko: "면허(증)", pos: "명사", exEn: "I finally got my driver's license.", exKo: "드디어 운전면허를 땄어요.", unit: "u227" },
  { id: "w473", en: "parking", ko: "주차", pos: "명사", exEn: "Parking is hard to find downtown.", exKo: "시내에선 주차 자리 찾기가 힘들어요.", unit: "u227" },
  { id: "w474", en: "gas", ko: "기름, 휘발유", pos: "명사", exEn: "We need to stop for gas.", exKo: "기름 넣으러 들러야 해요.", unit: "u227" },
  { id: "w475", en: "highway", ko: "고속도로", pos: "명사", exEn: "Take the highway to save time.", exKo: "시간 아끼려면 고속도로를 타세요.", unit: "u227" },
  { id: "w476", en: "seatbelt", ko: "안전벨트", pos: "명사", exEn: "Put on your seatbelt, please.", exKo: "안전벨트 매 주세요.", unit: "u227" },
  { id: "w477", en: "accident", ko: "사고", pos: "명사", exEn: "There was an accident on Main Street.", exKo: "메인 스트리트에서 사고가 났어요.", unit: "u227" },
  { id: "w478", en: "brake", ko: "브레이크(를 밟다)", pos: "명사", exEn: "Hit the brakes!", exKo: "브레이크 밟아!", unit: "u227" },
  { id: "w479", en: "lane", ko: "차선", pos: "명사", exEn: "Stay in your lane.", exKo: "차선을 지키세요.", unit: "u227" },
  { id: "w480", en: "pick up", ko: "데리러 가다, 찾아오다", pos: "구동사", exEn: "I'll pick you up at six.", exKo: "6시에 데리러 갈게요.", unit: "u227" },
  // u228 돈 쓰는 일상
  { id: "w481", en: "bill", ko: "청구서, 계산서", pos: "명사", exEn: "The electric bill came today.", exKo: "오늘 전기 요금 고지서가 왔어요.", unit: "u228" },
  { id: "w482", en: "change", ko: "거스름돈, 잔돈", pos: "명사", exEn: "Here's your change.", exKo: "여기 거스름돈이요.", unit: "u228" },
  { id: "w483", en: "tip", ko: "팁", pos: "명사", exEn: "How much should we tip?", exKo: "팁을 얼마나 줘야 하죠?", unit: "u228" },
  { id: "w484", en: "coupon", ko: "쿠폰", pos: "명사", exEn: "I have a coupon for ten percent off.", exKo: "10% 할인 쿠폰이 있어요.", unit: "u228" },
  { id: "w485", en: "wallet", ko: "지갑", pos: "명사", exEn: "I think I left my wallet at home.", exKo: "지갑을 집에 두고 온 것 같아요.", unit: "u228" },
  { id: "w486", en: "account", ko: "계좌, 계정", pos: "명사", exEn: "I opened a new bank account.", exKo: "새 은행 계좌를 만들었어요.", unit: "u228" },
  { id: "w487", en: "deposit", ko: "입금(하다), 보증금", pos: "명사", exEn: "You need to pay a deposit first.", exKo: "먼저 보증금을 내셔야 해요.", unit: "u228" },
  { id: "w488", en: "withdraw", ko: "(돈을) 인출하다", pos: "동사", exEn: "I need to withdraw some cash.", exKo: "현금을 좀 뽑아야 해요.", unit: "u228" },
  { id: "w489", en: "fee", ko: "수수료, 요금", pos: "명사", exEn: "Is there a delivery fee?", exKo: "배달 수수료가 있나요?", unit: "u228" },
  { id: "w490", en: "split", ko: "나누다, 나눠 내다", pos: "동사", exEn: "Let's split it fifty-fifty.", exKo: "반반씩 나눠 내요.", unit: "u228" },
  // u229 리액션 표현
  { id: "w491", en: "awesome", ko: "끝내주는, 최고인", pos: "형용사", exEn: "That concert was awesome!", exKo: "그 콘서트 진짜 끝내줬어!", unit: "u229" },
  { id: "w492", en: "amazing", ko: "놀라운, 굉장한", pos: "형용사", exEn: "The view from here is amazing.", exKo: "여기서 보는 경치가 굉장해요.", unit: "u229" },
  { id: "w493", en: "terrible", ko: "끔찍한, 형편없는", pos: "형용사", exEn: "The service there was terrible.", exKo: "거기 서비스는 형편없었어요.", unit: "u229" },
  { id: "w494", en: "weird", ko: "이상한", pos: "형용사", exEn: "That's weird. It was here a minute ago.", exKo: "이상하네. 방금 전까지 여기 있었는데.", unit: "u229" },
  { id: "w495", en: "gross", ko: "역겨운, 징그러운", pos: "형용사", exEn: "Ew, that's gross!", exKo: "웩, 그거 진짜 징그러워!", unit: "u229" },
  { id: "w496", en: "hilarious", ko: "완전 웃긴", pos: "형용사", exEn: "That movie was hilarious.", exKo: "그 영화 완전 웃겼어요.", unit: "u229" },
  { id: "w497", en: "unbelievable", ko: "믿을 수 없는", pos: "형용사", exEn: "Unbelievable! He won again.", exKo: "말도 안 돼! 그가 또 이겼어.", unit: "u229" },
  { id: "w498", en: "seriously", ko: "진심으로, 진짜로", pos: "부사", exEn: "Seriously? You're moving to Seattle?", exKo: "진짜? 시애틀로 이사 간다고?", unit: "u229" },
  { id: "w499", en: "exactly", ko: "정확히, 바로 그거야", pos: "부사", exEn: "Exactly! That's what I meant.", exKo: "바로 그거야! 내 말이 그 말이야.", unit: "u229" },
  { id: "w500", en: "totally", ko: "완전히", pos: "부사", exEn: "I totally forgot about it.", exKo: "그거 완전히 까먹고 있었어요.", unit: "u229" },
  // u320 필수 구동사 2
  { id: "w501", en: "check out", ko: "확인해 보다, 구경하다", pos: "구동사", exEn: "Check out this new cafe.", exKo: "이 새로 생긴 카페 한번 가 봐.", unit: "u320" },
  { id: "w502", en: "drop by", ko: "잠깐 들르다", pos: "구동사", exEn: "Drop by anytime this weekend.", exKo: "이번 주말에 아무 때나 들러요.", unit: "u320" },
  { id: "w503", en: "show up", ko: "나타나다, 오다", pos: "구동사", exEn: "He never showed up.", exKo: "그는 끝내 나타나지 않았어요.", unit: "u320" },
  { id: "w504", en: "work out", ko: "운동하다, 잘 풀리다", pos: "구동사", exEn: "I hope everything works out.", exKo: "다 잘 풀리길 바라요.", unit: "u320" },
  { id: "w505", en: "turn out", ko: "결국 ~로 드러나다", pos: "구동사", exEn: "It turned out to be a mistake.", exKo: "결국 실수였던 걸로 드러났어요.", unit: "u320" },
  { id: "w506", en: "end up", ko: "결국 ~하게 되다", pos: "구동사", exEn: "We ended up ordering pizza.", exKo: "결국 피자를 시켰어요.", unit: "u320" },
  { id: "w507", en: "hold on", ko: "잠깐 기다리다", pos: "구동사", exEn: "Hold on a second.", exKo: "잠깐만 기다려요.", unit: "u320" },
  { id: "w508", en: "bring up", ko: "(화제를) 꺼내다", pos: "구동사", exEn: "Why did you bring that up?", exKo: "왜 그 얘기를 꺼냈어?", unit: "u320" },
  { id: "w509", en: "calm down", ko: "진정하다", pos: "구동사", exEn: "Calm down and tell me what happened.", exKo: "진정하고 무슨 일인지 말해 봐요.", unit: "u320" },
  { id: "w510", en: "cheer up", ko: "기운 내다", pos: "구동사", exEn: "Cheer up! Tomorrow is another day.", exKo: "기운 내! 내일은 또 내일의 해가 떠.", unit: "u320" },
  // u321 미국식 캐주얼 표현
  { id: "w511", en: "grab", ko: "간단히 먹다, 급히 잡다", pos: "동사", exEn: "Want to grab lunch together?", exKo: "같이 점심 간단히 먹을래요?", unit: "u321" },
  { id: "w512", en: "stuff", ko: "것들, 물건", pos: "명사", exEn: "I have so much stuff to do today.", exKo: "오늘 할 일이 산더미예요.", unit: "u321" },
  { id: "w513", en: "hassle", ko: "번거로운 일", pos: "명사", exEn: "Returning it was such a hassle.", exKo: "반품하는 게 어찌나 번거롭던지.", unit: "u321" },
  { id: "w514", en: "heads-up", ko: "미리 알려주는 것", pos: "명사", exEn: "Thanks for the heads-up.", exKo: "미리 알려줘서 고마워요.", unit: "u321" },
  { id: "w515", en: "rain check", ko: "다음을 기약함", pos: "표현", exEn: "Can I take a rain check on dinner?", exKo: "저녁은 다음으로 미뤄도 될까요?", unit: "u321" },
  { id: "w516", en: "catch up", ko: "밀린 이야기를 나누다", pos: "구동사", exEn: "Let's catch up over coffee soon.", exKo: "조만간 커피 마시면서 밀린 얘기해요.", unit: "u321" },
  { id: "w517", en: "small talk", ko: "가벼운 잡담", pos: "명사", exEn: "I'm not good at small talk.", exKo: "저는 스몰토크를 잘 못해요.", unit: "u321" },
  { id: "w518", en: "my bad", ko: "내 잘못이야 (캐주얼 사과)", pos: "표현", exEn: "Oh, my bad. I sent the wrong file.", exKo: "아, 내 실수. 파일을 잘못 보냈네.", unit: "u321" },
  { id: "w519", en: "hang in there", ko: "조금만 버텨", pos: "표현", exEn: "Hang in there. It'll get better.", exKo: "조금만 버텨. 나아질 거야.", unit: "u321" },
  { id: "w520", en: "you bet", ko: "물론이지", pos: "표현", exEn: "Thanks for the ride! — You bet!", exKo: "태워줘서 고마워! — 당연하지!", unit: "u321" },
  // u322 생각과 판단
  { id: "w521", en: "perspective", ko: "관점, 시각", pos: "명사", exEn: "Try to see it from her perspective.", exKo: "그녀의 관점에서 보려고 해 봐요.", unit: "u322" },
  { id: "w522", en: "assume", ko: "추측하다, 가정하다", pos: "동사", exEn: "I assumed you already knew.", exKo: "당연히 알고 있는 줄 알았어요.", unit: "u322" },
  { id: "w523", en: "obvious", ko: "명백한, 뻔한", pos: "형용사", exEn: "The answer seems obvious to me.", exKo: "제겐 답이 뻔해 보여요.", unit: "u322" },
  { id: "w524", en: "convince", ko: "확신시키다, 설득하다", pos: "동사", exEn: "You don't have to convince me.", exKo: "저를 설득할 필요 없어요(이미 동의해요).", unit: "u322" },
  { id: "w525", en: "doubt", ko: "의심하다", pos: "동사", exEn: "I doubt it will rain today.", exKo: "오늘 비가 올 것 같지 않은데요.", unit: "u322" },
  { id: "w526", en: "consider", ko: "고려하다", pos: "동사", exEn: "Have you considered moving abroad?", exKo: "해외 이주를 고려해 본 적 있어요?", unit: "u322" },
  { id: "w527", en: "admit", ko: "인정하다", pos: "동사", exEn: "I admit I was wrong.", exKo: "제가 틀렸다는 걸 인정해요.", unit: "u322" },
  { id: "w528", en: "realize", ko: "깨닫다", pos: "동사", exEn: "I just realized I forgot her birthday.", exKo: "그녀 생일을 깜빡했다는 걸 방금 깨달았어요.", unit: "u322" },
  { id: "w529", en: "expect", ko: "기대하다, 예상하다", pos: "동사", exEn: "I didn't expect to see you here.", exKo: "여기서 만날 줄은 몰랐네요.", unit: "u322" },
  { id: "w530", en: "remind", ko: "상기시키다", pos: "동사", exEn: "Remind me to buy milk later.", exKo: "이따 우유 사라고 알려줘요.", unit: "u322" },
  // u323 감정 고급 2
  { id: "w531", en: "thrilled", ko: "정말 신난, 감격한", pos: "형용사", exEn: "I'm thrilled about the trip!", exKo: "여행 갈 생각에 완전 신나요!", unit: "u323" },
  { id: "w532", en: "terrified", ko: "겁에 질린", pos: "형용사", exEn: "I'm terrified of spiders.", exKo: "저는 거미가 무서워 죽겠어요.", unit: "u323" },
  { id: "w533", en: "confused", ko: "혼란스러운", pos: "형용사", exEn: "I'm confused. Can you explain again?", exKo: "헷갈려요. 다시 설명해 줄래요?", unit: "u323" },
  { id: "w534", en: "ashamed", ko: "부끄러운, 창피한", pos: "형용사", exEn: "There's nothing to be ashamed of.", exKo: "부끄러워할 것 하나도 없어요.", unit: "u323" },
  { id: "w535", en: "guilty", ko: "죄책감이 드는", pos: "형용사", exEn: "I feel guilty about canceling.", exKo: "취소해서 미안한 마음이에요.", unit: "u323" },
  { id: "w536", en: "lonely", ko: "외로운", pos: "형용사", exEn: "Moving to a new city can be lonely.", exKo: "새 도시로 이사하면 외로울 수 있어요.", unit: "u323" },
  { id: "w537", en: "bored", ko: "지루한", pos: "형용사", exEn: "I'm so bored. Let's do something.", exKo: "너무 심심해. 뭐라도 하자.", unit: "u323" },
  { id: "w538", en: "satisfied", ko: "만족한", pos: "형용사", exEn: "Are you satisfied with the result?", exKo: "결과에 만족하세요?", unit: "u323" },
  { id: "w539", en: "upset", ko: "속상한, 화가 난", pos: "형용사", exEn: "She's upset about the news.", exKo: "그녀는 그 소식에 속상해해요.", unit: "u323" },
  { id: "w540", en: "touched", ko: "감동한", pos: "형용사", exEn: "I was touched by your message.", exKo: "당신 메시지에 감동받았어요.", unit: "u323" },
  // u324 직장 생활 2
  { id: "w541", en: "shift", ko: "교대 근무", pos: "명사", exEn: "I'm working the night shift this week.", exKo: "이번 주는 야간 근무예요.", unit: "u324" },
  { id: "w542", en: "salary", ko: "급여, 연봉", pos: "명사", exEn: "The salary is negotiable.", exKo: "급여는 협의 가능해요.", unit: "u324" },
  { id: "w543", en: "raise", ko: "임금 인상", pos: "명사", exEn: "I'm going to ask for a raise.", exKo: "연봉 인상을 요청해 보려고요.", unit: "u324" },
  { id: "w544", en: "quit", ko: "그만두다", pos: "동사", exEn: "She quit her job last month.", exKo: "그녀는 지난달에 일을 그만뒀어요.", unit: "u324" },
  { id: "w545", en: "hire", ko: "고용하다", pos: "동사", exEn: "They're hiring right now.", exKo: "거기 지금 사람 뽑고 있어요.", unit: "u324" },
  { id: "w546", en: "fire", ko: "해고하다", pos: "동사", exEn: "He got fired for being late.", exKo: "그는 지각 때문에 해고됐어요.", unit: "u324" },
  { id: "w547", en: "interview", ko: "면접", pos: "명사", exEn: "I have a job interview on Friday.", exKo: "금요일에 취업 면접이 있어요.", unit: "u324" },
  { id: "w548", en: "resume", ko: "이력서", pos: "명사", exEn: "Update your resume first.", exKo: "먼저 이력서를 업데이트하세요.", unit: "u324" },
  { id: "w549", en: "benefits", ko: "복리후생", pos: "명사", exEn: "The company offers great benefits.", exKo: "그 회사는 복리후생이 좋아요.", unit: "u324" },
  { id: "w550", en: "retire", ko: "은퇴하다", pos: "동사", exEn: "My dad retires next year.", exKo: "아버지는 내년에 은퇴하세요.", unit: "u324" },
  // u325 온라인 쇼핑
  { id: "w551", en: "warranty", ko: "품질 보증(서)", pos: "명사", exEn: "It comes with a two-year warranty.", exKo: "2년 보증이 포함되어 있어요.", unit: "u325" },
  { id: "w552", en: "return", ko: "반품하다", pos: "동사", exEn: "Can I return this without the box?", exKo: "박스 없이도 반품할 수 있나요?", unit: "u325" },
  { id: "w553", en: "cart", ko: "장바구니, 카트", pos: "명사", exEn: "I added it to my cart.", exKo: "장바구니에 담아 놨어요.", unit: "u325" },
  { id: "w554", en: "checkout", ko: "결제(하기)", pos: "명사", exEn: "Enter the code at checkout.", exKo: "결제할 때 코드를 입력하세요.", unit: "u325" },
  { id: "w555", en: "shipping", ko: "배송(비)", pos: "명사", exEn: "Shipping is free over fifty dollars.", exKo: "50달러 이상이면 배송비가 무료예요.", unit: "u325" },
  { id: "w556", en: "tracking", ko: "배송 조회", pos: "명사", exEn: "Here's your tracking number.", exKo: "여기 운송장 번호예요.", unit: "u325" },
  { id: "w557", en: "secondhand", ko: "중고의", pos: "형용사", exEn: "I bought a secondhand bike.", exKo: "중고 자전거를 샀어요.", unit: "u325" },
  { id: "w558", en: "browse", ko: "둘러보다", pos: "동사", exEn: "I was just browsing online stores.", exKo: "그냥 온라인 매장들을 둘러보고 있었어요.", unit: "u325" },
  { id: "w559", en: "subscription", ko: "구독", pos: "명사", exEn: "I canceled my streaming subscription.", exKo: "스트리밍 구독을 해지했어요.", unit: "u325" },
  { id: "w560", en: "expire", ko: "만료되다", pos: "동사", exEn: "The coupon expires tonight.", exKo: "그 쿠폰은 오늘 밤에 만료돼요.", unit: "u325" },
  // u326 병원과 운동
  { id: "w561", en: "symptom", ko: "증상", pos: "명사", exEn: "What symptoms do you have?", exKo: "어떤 증상이 있으세요?", unit: "u326" },
  { id: "w562", en: "prescription", ko: "처방전", pos: "명사", exEn: "You need a prescription for that.", exKo: "그건 처방전이 필요해요.", unit: "u326" },
  { id: "w563", en: "pill", ko: "알약", pos: "명사", exEn: "Take one pill twice a day.", exKo: "하루에 두 번, 한 알씩 드세요.", unit: "u326" },
  { id: "w564", en: "surgery", ko: "수술", pos: "명사", exEn: "The surgery went well.", exKo: "수술은 잘 됐어요.", unit: "u326" },
  { id: "w565", en: "emergency", ko: "응급 상황", pos: "명사", exEn: "Call 911 in an emergency.", exKo: "응급 상황에는 911에 전화하세요.", unit: "u326" },
  { id: "w566", en: "therapy", ko: "치료, 상담", pos: "명사", exEn: "Physical therapy helped a lot.", exKo: "물리 치료가 많이 도움됐어요.", unit: "u326" },
  { id: "w567", en: "workout", ko: "운동", pos: "명사", exEn: "That was a great workout.", exKo: "정말 운동 제대로 했네요.", unit: "u326" },
  { id: "w568", en: "jog", ko: "조깅하다", pos: "동사", exEn: "I jog along the river every morning.", exKo: "저는 매일 아침 강가에서 조깅해요.", unit: "u326" },
  { id: "w569", en: "gym", ko: "헬스장", pos: "명사", exEn: "I signed up for a gym membership.", exKo: "헬스장 회원권을 끊었어요.", unit: "u326" },
  { id: "w570", en: "sore", ko: "아픈, 쑤시는", pos: "형용사", exEn: "My legs are sore from yesterday.", exKo: "어제 운동 때문에 다리가 쑤셔요.", unit: "u326" },
  // u327 관계의 기술
  { id: "w571", en: "support", ko: "지지하다, 응원하다", pos: "동사", exEn: "I'll always support your decision.", exKo: "당신 결정을 항상 지지할게요.", unit: "u327" },
  { id: "w572", en: "comfort", ko: "위로하다", pos: "동사", exEn: "She comforted me when I was down.", exKo: "제가 힘들 때 그녀가 위로해 줬어요.", unit: "u327" },
  { id: "w573", en: "encourage", ko: "격려하다", pos: "동사", exEn: "My teacher encouraged me to apply.", exKo: "선생님이 지원해 보라고 격려해 주셨어요.", unit: "u327" },
  { id: "w574", en: "appreciate", ko: "고마워하다", pos: "동사", exEn: "I really appreciate your help.", exKo: "도와주셔서 정말 감사해요.", unit: "u327" },
  { id: "w575", en: "rely", ko: "의지하다", pos: "동사", exEn: "You can rely on me.", exKo: "저한테 의지해도 돼요.", unit: "u327" },
  { id: "w576", en: "ignore", ko: "무시하다", pos: "동사", exEn: "Just ignore the rude comments.", exKo: "무례한 댓글은 그냥 무시하세요.", unit: "u327" },
  { id: "w577", en: "judge", ko: "판단하다, 재단하다", pos: "동사", exEn: "Don't judge people by their looks.", exKo: "사람을 겉모습으로 판단하지 마세요.", unit: "u327" },
  { id: "w578", en: "gossip", ko: "험담(하다)", pos: "명사", exEn: "I try to stay out of office gossip.", exKo: "저는 사내 험담에 끼지 않으려 해요.", unit: "u327" },
  { id: "w579", en: "compliment", ko: "칭찬(하다)", pos: "명사", exEn: "Thanks for the compliment!", exKo: "칭찬 고마워요!", unit: "u327" },
  { id: "w580", en: "make up", ko: "화해하다", pos: "구동사", exEn: "They fought but made up quickly.", exKo: "그들은 싸웠지만 금방 화해했어요.", unit: "u327" },
  // u328 사회와 공동체
  { id: "w581", en: "inflation", ko: "물가 상승, 인플레이션", pos: "명사", exEn: "Inflation is making everything expensive.", exKo: "물가 상승으로 모든 게 비싸지고 있어요.", unit: "u328" },
  { id: "w582", en: "unemployment", ko: "실업(률)", pos: "명사", exEn: "Unemployment is falling slowly.", exKo: "실업률이 천천히 떨어지고 있어요.", unit: "u328" },
  { id: "w583", en: "housing", ko: "주거, 주택", pos: "명사", exEn: "Housing prices keep going up.", exKo: "집값이 계속 오르고 있어요.", unit: "u328" },
  { id: "w584", en: "community", ko: "지역 사회, 커뮤니티", pos: "명사", exEn: "She's active in the local community.", exKo: "그녀는 지역 사회 활동에 적극적이에요.", unit: "u328" },
  { id: "w585", en: "charity", ko: "자선 (단체)", pos: "명사", exEn: "All profits go to charity.", exKo: "수익금은 전부 자선 단체에 기부돼요.", unit: "u328" },
  { id: "w586", en: "volunteer", ko: "자원봉사(하다)", pos: "동사", exEn: "I volunteer at the shelter on weekends.", exKo: "주말마다 보호소에서 봉사해요.", unit: "u328" },
  { id: "w587", en: "donate", ko: "기부하다", pos: "동사", exEn: "We donated old clothes.", exKo: "우리는 헌 옷을 기부했어요.", unit: "u328" },
  { id: "w588", en: "vote", ko: "투표하다", pos: "동사", exEn: "Did you vote in the last election?", exKo: "지난 선거에서 투표했어요?", unit: "u328" },
  { id: "w589", en: "law", ko: "법", pos: "명사", exEn: "It's against the law.", exKo: "그건 법에 어긋나요.", unit: "u328" },
  { id: "w590", en: "fair", ko: "공정한", pos: "형용사", exEn: "That's not fair!", exKo: "그건 공평하지 않아!", unit: "u328" },
  // u329 계획과 목표
  { id: "w591", en: "goal", ko: "목표", pos: "명사", exEn: "My goal is to run a marathon.", exKo: "제 목표는 마라톤 완주예요.", unit: "u329" },
  { id: "w592", en: "achieve", ko: "달성하다", pos: "동사", exEn: "You can achieve anything you want.", exKo: "원하는 건 뭐든 이룰 수 있어요.", unit: "u329" },
  { id: "w593", en: "effort", ko: "노력", pos: "명사", exEn: "It takes time and effort.", exKo: "시간과 노력이 필요해요.", unit: "u329" },
  { id: "w594", en: "progress", ko: "진전, 발전", pos: "명사", exEn: "You're making great progress!", exKo: "정말 잘 늘고 있어요!", unit: "u329" },
  { id: "w595", en: "challenge", ko: "도전 (과제)", pos: "명사", exEn: "Learning English is a fun challenge.", exKo: "영어 배우기는 즐거운 도전이에요.", unit: "u329" },
  { id: "w596", en: "opportunity", ko: "기회", pos: "명사", exEn: "Don't miss this opportunity.", exKo: "이 기회를 놓치지 마세요.", unit: "u329" },
  { id: "w597", en: "decision", ko: "결정", pos: "명사", exEn: "It was a tough decision.", exKo: "어려운 결정이었어요.", unit: "u329" },
  { id: "w598", en: "focus", ko: "집중하다", pos: "동사", exEn: "Focus on one thing at a time.", exKo: "한 번에 한 가지에만 집중하세요.", unit: "u329" },
  { id: "w599", en: "commit", ko: "전념하다, 약속하다", pos: "동사", exEn: "I'm committed to studying every day.", exKo: "매일 공부하기로 굳게 마음먹었어요.", unit: "u329" },
  { id: "w600", en: "determined", ko: "굳게 결심한", pos: "형용사", exEn: "She's determined to pass the test.", exKo: "그녀는 시험에 붙겠다고 단단히 결심했어요.", unit: "u329" },
]);
// end of data2.js
