// ============================================================
// 단어 활용 팁 (뉘앙스 · 헷갈리는 표현 · 발음 주의)
// 단어 카드 아래에 💡로 표시됩니다. 원하는 단어에 자유롭게 추가하세요.
// ============================================================

const TIPS = {
  // Lv.1
  w005: "가볍게 부딪혔을 땐 Sorry., 정중하게는 I'm so sorry. 라고 해요.",
  w006: "말을 걸거나 지나갈 때 쓰는 말. 사과할 때는 sorry를 써요.",
  w043: "'만나다' 뜻으로도 자주 써요. See you! = 또 봐!",
  w046: "일하다 외에 '작동하다' 뜻도. It works! = 된다!",
  w056: "오른쪽 외에 '맞은'(That's right), '권리' 뜻도 있어요.",
  w077: "괜찮다 외에 '벌금'이라는 뜻도 있어요.",

  // Lv.2
  w101: "'빌려오다'예요. 빌려주다는 lend. Can I borrow ~?로 부탁해요.",
  w102: "borrow와 방향이 반대. lend + 사람 + 물건 순서로 써요.",
  w103: "고장 수리 외에 '(날짜·일정을) 정하다'로도 써요. fix a date.",
  w104: "lose-lost-lost. '길을 잃다'는 get lost라고 해요.",
  w105: "충전 외에 '(요금을) 청구하다' 뜻도 흔해요. How much do you charge?",
  w107: "쓰레기를 버릴 때 쓰고, '기회를 날리다'로도 써요.",
  w108: "끄다는 turn off, 소리를 키우다는 turn up.",
  w109: "이사 외에 '감동시키다' 뜻도. a moving story = 감동적인 이야기.",
  w111: "매일 반복하는 일. morning routine처럼 써요.",
  w112: "집과 직장(학교)을 오가는 것에만 써요.",
  w117: "병원·미용실처럼 '시간을 잡는 예약'. 친구와의 약속은 plans.",
  w120: "ahead of schedule = 예정보다 빨리, behind schedule = 늦게.",
  w123: "believe는 '말을 믿다', trust는 '사람을 신뢰하다'에 가까워요.",
  w128: "I promise. 한마디로 '약속할게'가 돼요.",
  w131: "긴장·초조하다는 뜻. '신경질적인'이 아니에요.",
  w132: "내가 창피한 것. 남을 창피하게 만드는 것은 embarrassing.",
  w133: "내가 실망한 것. 실망스러운 대상은 disappointing.",
  w139: "뜻대로 안 돼 답답한 느낌. 화남(angry)보다 무력감에 가까워요.",
  w145: "맛의 '종류'를 뜻해요. vanilla flavor. 미각 자체는 taste.",
  w149: "주문 외에 '순서, 명령' 뜻도. out of order = 고장.",
  w150: "보통 복수형 leftovers로 써요.",
  w155: "'식단' 전체를 뜻해요. 다이어트 중이다 = be on a diet.",
  w156: "사고로 인한 부상. 병은 illness, 베인 상처는 wound.",
  w161: "can/can't와 함께 써요. can't afford = (돈·시간) 형편이 안 됨.",
  w162: "환불받다 = get a refund. 동사로도 써요.",
  w164: "반대말은 quantity(양)예요.",
  w169: "싸게 잘 산 물건. '흥정하다'라는 동사 뜻도 있어요.",
  w174: "be delayed = 지연되다. 비행기·기차 안내에 자주 나와요.",
  w175: "환승 외에 계좌 이체, 부서 이동에도 써요.",
  w179: "반대말은 arrival(도착). 공항 표지판 필수 단어예요.",
  w183: "cold보다 훨씬 추울 때. I'm freezing! = 얼어 죽겠어!",
  w186: "열이 있다 = have a temperature 또는 have a fever.",
  w191: "in my opinion = 제 생각에는. 채팅에선 IMO로 줄여요.",
  w192: "agree with + 사람/의견. 간단히 I agree. = 맞아요.",
  w194: "suggest 뒤엔 -ing! suggest going(O), suggest to go(X).",
  w197: "Don't mention it. = 별말씀을요(천만에요).",
  w199: "설득해서 '하게 만들다'. convince는 '믿게 만들다'에 가까워요.",

  // Lv.3
  w301: "직장 동료. coworker와 같은 뜻이에요. 발음은 [칼리-그].",
  w302: "meet the deadline = 마감을 지키다, miss = 놓치다.",
  w304: "승진 외에 '판촉, 홍보' 뜻도 있어요.",
  w305: "격식 있는 표현. 일상 대화에선 quit을 더 많이 써요.",
  w306: "work overtime = 야근하다. 야근 수당이라는 뜻도 있어요.",
  w309: "적은 노력으로 좋은 결과를 내는 것. effective는 '효과가 있는'.",
  w311: "on a budget = 한정된 예산으로, 아껴 쓰는 중.",
  w313: "at the company's expense = 회사 부담으로.",
  w314: "invest in ~에 투자하다. 돈뿐 아니라 시간·노력에도 써요.",
  w316: "b는 묵음! 발음은 [데트]. in debt = 빚진 상태.",
  w319: "be worth -ing = ~할 가치가 있다. It's worth it! = 그만한 가치가 있어!",
  w322: "보험 증권이라는 뜻도 있어요. insurance policy.",
  w326: "셀 수 없는 명사라 an evidence(X), some evidence(O).",
  w328: "problem보다 중립적인 말. 동사로 '발행하다' 뜻도 있어요.",
  w329: "in public = 사람들 앞에서, 공공장소에서.",
  w331: "돈뿐 아니라 시간·마음을 아낌없이 내주는 것에도 써요.",
  w332: "부정적 뉘앙스예요. 좋게 말하면 determined(단호한).",
  w334: "h는 묵음! 발음은 [어니스트]. to be honest = 솔직히 말하면.",
  w337: "sensible(분별 있는)과 헷갈리기 쉬워요. sensitive = 예민한.",
  w338: "rely(의지하다) + able. 사물에도 써요. a reliable car.",
  w340: "명사로는 '환자'라는 뜻. 문맥으로 구분해요.",
  w341: "격식 표현. 일상 회화에선 put off를 더 많이 써요.",
  w344: "캐주얼하게는 right away를 많이 써요.",
  w346: "임시직 직원을 temp라고 줄여 불러요.",
  w348: "It's urgent. = 급한 일이야.",
  w350: "'(시간이 걸려) 결국'. finally는 '(기다리던 것이) 마침내'.",
  w352: "cause and effect = 원인과 결과. 동사로 '일으키다'.",
  w354: "avoid 뒤엔 -ing! avoid going(O), avoid to go(X).",
  w356: "complain about ~에 대해 불평하다. 명사는 complaint.",
  w357: "I can handle it. = 내가 처리할 수 있어. '문손잡이' 뜻도.",
  w360: "affect(동사: 영향을 주다)와 구분하세요. effect는 주로 명사.",
  w361: "give up on + 사람 = ~에 대한 기대를 접다.",
  w362: "to 뒤에 명사/-ing가 와요! look forward to seeing(O), to see(X).",
  w363: "We're running out of time. = 시간이 다 돼 가.",
  w365: "고민해서 '알아내다'. find out은 정보를 '알게 되다'.",
  w367: "문제·사람을 상대하다. It's not a big deal. = 별거 아니야.",
  w369: "to 뒤에 -ing. '~하곤 했다'의 used to와는 달라요.",
  w371: "감당이 안 될 만큼 벅찰 때. 좋은 의미의 감동에도 써요.",
  w372: "be anxious to + 동사 = 몹시 ~하고 싶다.",
  w373: "어색한 분위기·사이를 표현하는 딱 맞는 단어예요.",
  w374: "tired의 훨씬 강한 버전. 완전히 방전된 상태.",
  w377: "different(다른)와 무관해요! in+different = 무관심한.",
  w380: "형용사일 땐 [컨텐트]로 뒤에 강세. 명사 '콘텐츠'와 강세가 달라요.",
};
// end of tips.js
